name: Build
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# No build on push for now #
on: 
  workflow_dispatch: 
  
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run electron:linux
    - name: publish
      run: npm publish

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run electron:mac
    - name: publish
      run: npm publish

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run electron:windows
    - name: publish
      run: npm publish
