name: Build - All platforms
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
    #push:
    workflow_dispatch:

jobs:
    build_on_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install rpm and libarchive
              run: sudo apt install rpm libarchive-tools
            - name: install dependencies
              run: npm install
            - name: build
              run: npm run electron:linux
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                path: 'package.json'
                prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                name: dopamine-artifacts-linux
                path: |
                    ${{ github.workspace }}
                    */release
                    ./release
                    ./release/Dopamine-${{ steps.ver_name.outputs.prop }}.rpm
                    ${{ github.workspace }}/Dopamine-${{ steps.ver_name.outputs.prop }}.rpm
                #dopamine/release/Dopamine-${{ steps.ver_name.outputs.prop }}.rpm
                #dopamine/release/Dopamine-${{ steps.ver_name.outputs.prop }}.deb
                #dopamine/release/Dopamine-${{ steps.ver_name.outputs.prop }}.AppImage
                #dopamine/release/Dopamine-${{ steps.ver_name.outputs.prop }}.snap
                #dopamine/release/Dopamine-${{ steps.ver_name.outputs.prop }}.pacman

    build_on_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: npm install
            - name: build
              run: npm run electron:mac
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                path: 'package.json'
                prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                name: dopamine-artifacts-macos
                path: 
                    release/Dopamine-${{ steps.ver_name.outputs.prop }}.dmg
                    

    build_on_win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: npm install
            - name: build
              run: npm run electron:windows
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                path: 'package.json'
                prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                name: dopamine-artifacts-win
                path: release\Dopamine-${{ steps.ver_name.outputs.prop }}.exe
                    
